name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: Ruff Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."